In [1]:
import numpy as np

In [2]:
a=np.arange(12).reshape(3,4)

In [4]:
#------------------------------printing all the number in the lsit:------------------# 
for i in range(0,3):
    for j in range(0,4):
        print(a[i][j])
#-------------------------Alternative way:----------------------#
for i in a:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11


In [5]:
#---------------------(np.nditer)it is the most sofasticated way of trvaersing in an array
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
#---------------------order='C' going row by row and printing the each element:------------
for i in np.nditer(a,order='C'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
#-------------------------#order='F' going column by column and printing the each element:---------------
for i in np.nditer(a,order='F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [14]:
#-------------------------print ecah columns but in the array form ex->[1,2,3]------------------
for i in np.nditer(a,order='F',flags=['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [15]:

#-> ---------------op_flags='readwrite' helps in the for reading opreation directly in the same array:--------------- 
#eaxmple we are doing sqaure opration in the same 'a' array
for i in np.nditer(a,op_flags=['readwrite']):
    i[...]=i*i
#-----Alternative way:-----------------#
for i in range(0,len(a)):
    for j in range(0,len(a[0])):
        a[i][j]=a[i][j]*a[i][j]


In [16]:
b=np.arange(1,4).reshape(3,1)
print(b)
#-------------taking elemnent from 'a'array and taking elemnet from 'b' array #-> the secondary array should be boradcastable:--------
for i,j in np.nditer([a,b]):
    print(i,j)




[[1]
 [2]
 [3]]
0 1
1 1
16 1
81 1
256 2
625 2
1296 2
2401 2
4096 3
6561 3
10000 3
14641 3
